version: '3.7'
services:
  mongo-server:
    container_name: mongo_db
    image: 'mongo'
    restart: always
    env_file:
      ./server/docker/mongoDB.env
    ports:
      - 27017:27017
    volumes:
      - ./server/database/mongoDB/db-init/:/docker-entrypoint-initdb.d
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
